### ISSUE TITLE
Post-2.4 OpenCV versions

### ISSUE THREAD

**Issue by levingerdes** [rock-perception/perception-stereo#4]
I am trying to switch from Ubuntu 16.04 LTS to 18.04 LTS and I cannot compile `perception/stereo` with recent versions of OpenCV (`pkg-config --modversion opencv` yields version 3.2.0), because the legacy modules have been removed in OpenCV 3.0:

https://docs.opencv.org/3.0.0/db/dfa/tutorial_transition_guide.html#tutorial_transition_overview

This leads to the following error:

```
perception/stereo(/home/user/rock/perception/stereo): failed in build phase
    'make --jobserver-fds=7,8 -j' returned status 2
    see /home/user/rock/install/log/perception/stereo-build.log for details
    last 10 lines are:

    /home/user/rock/perception/stereo/src/psurf.h:9:10: fatal error: opencv2/legacy/compat.hpp: No such file or directory
     #include <opencv2/legacy/compat.hpp>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    src/CMakeFiles/stereo.dir/build.make:158: recipe for target 'src/CMakeFiles/stereo.dir/psurf.cpp.o' failed

```

Some includes would need to be adapted, too. For example, `#include "opencv2/core/internal.hpp"` should be `#include "opencv2/core.hpp"` in the more recent OpenCV.

Are there plans to update this package soon or should I install a specific version of OpenCV (probably 2.4)? It's compiling in Ubuntu 16.04 (where `pkg-config --modversion opencv` yields version 2.4.9.1).

**Comment by levingerdes** [comment]
Are this package and [the orogen task](https://github.com/rock-perception/perception-orogen-stereo) deprecated in favor of [orogen/image_preprocessing](https://github.com/rock-perception/perception-orogen-image_preprocessing)? Or do you still plan to update this?

**Comment by chhtz** [comment]
Nobody seemed to feel responsible for this anymore. Do you have a working patch for this already? Then a PR would be very welcome! (Otherwise, I can have a look into that, hopefully by next week)

**Comment by chhtz** [comment]
I had a look into this (especially the history of the files), and the `psurf.{h,cpp}` files appear to be a copy from OpenCV with some (i.e., a lot of) modifications by @jakobs 

Porting this to 3.x probably will be more effort than I originally assumed/hoped. So main questions are:
 * Is this functionality actually still used/required? (I assume this is only used directly by `perception/stereo/src/sparse_stereo.cpp`, which is using it, when configured with `envire::DESCRIPTOR_PSURF` (instead of `envire::DESCRIPTOR_SURF`), but I really can't tell for sure)
* If we want to make this 3.x compatible, I see two options:
  * Replace every legacy function call by the corresponding 3.x function.
  * Work out what changed between the original and try to apply the same changes to the corresponding opencv function from an up-to-date version.

A fast, pragmatic solution would be to deactivate PSURF for OpenCV 3.x and throw some error message with a link to this issue (or a new issue), i.e., postponing a real solution until somebody actually needs this.

**Comment by m0rsch1** [comment]
At DFKI, what do we use for stereo image processing? Maybe we could get rid of this package anyway?

**Comment by levingerdes** [comment]
Thank you all so much for your comments and sorry for only managing to come back now.

When I checked the package (not in more detail than you did), I came to the same conclusion: I don't think it's worth it to fix this package if we then end up being the only ones using it. And I assume you have already switched to a different stereo processing pipeline at DFKI, right? While switching over to that approach also entails some work, I think it's a much better way forward.

Can you maybe give us some pointers in this regard? Any tips would be appreciated! I will then close this issue and transition to your newer approach.

The repo could be marked as deprecated or its dependency on OpenCV 2.4 could be stated prominently until its use with PSURF features is required, as you suggested.

**Comment by chhtz** [comment]
@levingerdes It appears that at our institute nobody is actually doing "manual" stereo anymore. So from our side it would be fine to either deprecate the entire packet, or to remove the PSURF functionality.

If you do need the PSURF functionality and have the time to provide a patch, we would of course also be happy to push that upstream (from my last glance over it, this should not be too complicated, but you'd need to work through a few hundred lines of code).

**Comment by levingerdes** [comment]
@chhtz, thanks for checking! This really helps us understand the situation better. We will remove the PSURF functionality for now and reference this issue in the coming commit to explain why.
